server:
  port: 9090

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.234.144.78:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xxxx.springboot.vo
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  auto-dialect: mysql

logging:
  pattern:
    console: "%d{yyyy-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  level:
    com:
      xxxx:
        springboot:
          dao: debug
  file:
    path: "."
    name: "springboot.log"
    max-size: "10MB"